### PR TITLE
[Chore] Reduce renovate noise

### PR DESCRIPTION
**Pull request by Redmega**
Added a schedule to the renovate PRs for dev dependencies, and enabled automerging for everything but major version changes.

Is the schedule of once a month frequent enough, or should we merge more frequently?

### CODE REVIEW

**Comment by rdela** [comment]
How about every Sunday?

**Comment by rdela** [comment]
But you know me, I am a merge early and often person so happy to adjust to whatever cadence others prefer

**Comment by Redmega** [comment]
Looks like node-6 fails randomly. Do we need to give the test more time?

```
returns true if the query contains a faulty keyword

Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

**Comment by hmeissner** [comment]
Timeout in tests is no longer an issue with https://github.com/GraphCMS/gatsby-source-graphcms/pull/24

**Pull request merged**
